# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 173fdf9f5ce966cfa18e353e1847d1c8e1c6777af3e0f96f62ebbac15ca6eedd2ef8d96501dfb86571807b8eed3b19f757b2598c379b3bf92d88618578a9b7a0

test:
  secret_key_base: 98812c5216f940c0842a7100a843190547442ef142e7b25b1ff4df45029258af783dcb9b836cbff7600dcbdfdffe524767ba283e73753a5d12c32279c0deb50c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
